### ISSUE TITLE
Unknown deploy error

### ISSUE THREAD

**Issue by dalghost** [serverless/serverless-graphql-apollo#100]
### Complite Deploy
```
1. aws configure
2. sls create --template aws-nodejs --path test-serverless
3. sls deploy -v
```

### Error Deploy
```
1. aws configure
2. sls install -u https://github.com/serverless/serverless-graphql-apollo
3. yarn
4.<your-s3-bucket-name> => aojweoifjw-graphql-test
5. npm run deploy
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle serverless-graphql-apollo@0.0.0~predeploy: serverless-graphql-apollo@0.0.0
6 silly lifecycle serverless-graphql-apollo@0.0.0~predeploy: no script for predeploy, continuing
7 info lifecycle serverless-graphql-apollo@0.0.0~deploy: serverless-graphql-apollo@0.0.0
8 verbose lifecycle serverless-graphql-apollo@0.0.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle serverless-graphql-apollo@0.0.0~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/user/TempDeveloper/serverless-graphql-apollo/node_modules/.bin:/Applications/CMake.app/Contents/bin/:/Users/user/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/CMake.app/Contents/bin/:/Users/user/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin
10 verbose lifecycle serverless-graphql-apollo@0.0.0~deploy: CWD: /Users/user/TempDeveloper/serverless-graphql-apollo
11 silly lifecycle serverless-graphql-apollo@0.0.0~deploy: Args: [ '-c', 'npm run deploy:api && npm run deploy:frontend' ]
12 silly lifecycle serverless-graphql-apollo@0.0.0~deploy: Returned: code: 1  signal: null
13 info lifecycle serverless-graphql-apollo@0.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: serverless-graphql-apollo@0.0.0 deploy: `npm run deploy:api && npm run deploy:frontend`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid serverless-graphql-apollo@0.0.0
16 verbose cwd /Users/user/TempDeveloper/serverless-graphql-apollo
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error serverless-graphql-apollo@0.0.0 deploy: `npm run deploy:api && npm run deploy:frontend`
22 error Exit status 1
23 error Failed at the serverless-graphql-apollo@0.0.0 deploy script 'npm run deploy:api && npm run deploy:frontend'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the serverless-graphql-apollo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run deploy:api && npm run deploy:frontend
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs serverless-graphql-apollo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls serverless-graphql-apollo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dal2** [comment]
### fail
reboot
re create Access Keys

### complite
only waitting 1~3hour and "npm run deploy"

i don't understand this effect

**Comment by dal2** [comment]
#1877

**Comment by sid88in** [comment]
@dalghost these errors should go away now. Please try again.
