### ISSUE TITLE
SyntaxError: Unterminated regular expression (1:2)

### ISSUE THREAD

**Issue by scotttesler** [serverless/serverless-graphql-apollo#79]
Node version 7.4.0
NPM version 4.0.5

```
npm start

> serverless-graphql-apollo@0.0.0 start /Users/scott/Documents/Other/serverless-graphql-apollo
> npm run generate:config:local && MOCKED_DATABASE=true env-cmd foundation/environment/security.env.local nodemon ./foundation/devServer --ignore app --exec babel-node


> serverless-graphql-apollo@0.0.0 generate:config:local /Users/scott/Documents/Other/serverless-graphql-apollo
> env-cmd foundation/environment/security.env.local npm run generate:config


> serverless-graphql-apollo@0.0.0 generate:config /Users/scott/Documents/Other/serverless-graphql-apollo
> node foundation/generateConfig/index.js

api/config.js file was generated
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./foundation/devServer`
App is now running on http://localhost:3000
{ SyntaxError: Unterminated regular expression (1:2)
    at Parser.pp$4.raise (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2454:13)
    at Parser.pp$7.readRegexp (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:3023:51)
    at Parser.pp$7.readToken_slash (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2843:50)
    at Parser.pp$7.getTokenFromCode (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2969:17)
    at Parser.pp$7.readToken (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2714:15)
    at Parser.pp$7.nextToken (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2705:13)
    at Parser.pp$7.next (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2650:8)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:2010:10)
    at Parser.pp$3.parseExprAtom (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1960:17)
    at Parser.parseExprAtom (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn-dynamic-import/lib/inject.js:55:31)
    at Parser.pp$3.parseExprSubscripts (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1854:19)
    at Parser.pp$3.parseMaybeUnary (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1831:17)
    at Parser.pp$3.parseExprOps (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1773:19)
    at Parser.pp$3.parseMaybeConditional (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1756:19)
    at Parser.pp$3.parseMaybeAssign (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1733:19)
    at Parser.pp$3.parseExpression (/Users/scott/Documents/Other/serverless-graphql-apollo/node_modules/acorn/dist/acorn.js:1709:19) pos: 2, loc: Position { line: 1, column: 2 }, raisedAt: 10 }
webpack built f9904cf31dc89f8bbce2 in 4484ms
```

**Comment by mpigsley** [comment]
@scotttesler Is it running now?

**Comment by nikgraf** [comment]
Will switch to create-react-app in a PR soon and then this shouldn't be an issue anymore.
