### ISSUE TITLE
graphql-relay

### ISSUE THREAD

**Issue by marc-at** [serverless/serverless-graphql-apollo#91]
Looks like you removed graphql-relay as a dependency.  I see that graphql/types/user.js still references it though:
```
import {
  GraphQLObjectType,
  GraphQLString,
} from 'graphql';
import {
  globalIdField,
} from 'graphql-relay';
```

I end up with the following error:

> [nodemon] 1.11.0
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `babel-node ./foundation/devServer`
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'graphql-relay'

Is the plan to completely remove all use of relay?

**Comment by geirman** [comment]
I'm stuck dead in the water. Here's what I've done...

1. cloned the repo
2. `$ yarn`
3. `$ npm start`

And I get this output...

```
api/config.js file was generated
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./foundation/devServer`
module.js:471
    throw err;
    ^

Error: Cannot find module 'graphql-relay'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/dev/serverless-graphql-apollo/graphql/types/user.js:7:1)
    at Module._compile (module.js:570:32)
    at loader (/dev/serverless-graphql-apollo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/dev/serverless-graphql-apollo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting..
```

**Comment by marc-at** [comment]
It doesn't look it is on the master branch yet.  The develop branch has the fix.  You can probably just paste the update from https://github.com/andykenward/serverless-graphql-apollo/commit/ca3cbc5c1ffc06519982ed3902a010020259af7d too.

**Comment by geirman** [comment]
Worked perfectly, thanks @marc-at!

**Comment by colllin** [comment]
You can also just `yarn add graphql-relay`

**Comment by nikgraf** [comment]
just removed it in a cleanup PR https://github.com/serverless/serverless-graphql-apollo/pull/95
